module.exports = [
    "A reader lives a thousand lives before he dies.",
    "Books are a uniquely portable magic.",
    "The man who does not read has no advantage over the man who cannot read.",
    "Reading is essential for those who seek to rise above the ordinary.",
    "The more you read, the more things you will know.",
    "Reading gives us someplace to go when we have to stay where we are.",
    "Once you learn to read, you will be forever free.",
    "Today a reader, tomorrow a leader.",
    "Reading is to the mind what exercise is to the body.",
    "There is no friend as loyal as a book.",
    "A book is a dream that you hold in your hands.",
    "The only thing that you absolutely have to know, is the location of the library.",
    "Books wash away from the soul the dust of everyday life.",
    "We read to know we are not alone.",
    "Until I feared I would lose it, I never loved to read. One does not love breathing.",
    "Books are mirrors: you only see in them what you already have inside you.",
    "Reading brings us unknown friends.",
    "I have always imagined that Paradise will be a kind of library.",
    "No two persons ever read the same book.",
    "There is more treasure in books than in all the pirate’s loot on Treasure Island.",
    "A house without books is like a room without windows.",
    "Books are the quietest and most constant of friends.",
    "Reading furnishes the mind only with materials of knowledge.",
    "I do believe something very magical can happen when you read a good book.",
    "A good book is an event in my life.",
    "The worth of a book is to be measured by what you can carry away from it.",
    "Reading is dreaming with open eyes.",
    "Books are a uniquely portable magic.",
    "Reading one book is like eating one potato chip.",
    "That’s the thing about books. They let you travel without moving your feet.",
    "Books are the plane, and the train, and the road. They are the destination and the journey.",
    "Reading is not optional.",
    "In the end, we’ll all become stories.",
    "I read a book one day and my whole life was changed.",
    "Reading is a discount ticket to everywhere.",
    "Books are a refuge, a sort of cloistral refuge, from the vulgarities of the actual world.",
    "If you don’t like to read, you haven’t found the right book.",
    "Books are my plane, and my train, and my road.",
    "So many books, so little time.",
    "Books are the treasured wealth of the world and the fit inheritance of generations and nations.",
    "Read the best books first, or you may not have a chance to read them at all.",
    "There is no frigate like a book to take us lands away.",
    "Books open your mind, broaden your mind, and strengthen you as nothing else can.",
    "To learn to read is to light a fire.",
    "You can never get a cup of tea large enough or a book long enough to suit me.",
    "You think your pain and your heartbreak are unprecedented in the history of the world, but then you read.",
    "Keep reading. It’s one of the most marvelous adventures anyone can have.",
    "Reading is the gateway for children that makes all other learning possible.",
    "Books are the bees which carry the quickening pollen from one to another mind.",
    "Reading is the basic tool in the living of a good life.",
    "He that loves reading has everything within his reach.",
    "You don’t have to burn books to destroy a culture. Just get people to stop reading them.",
    "Books can be dangerous. The best ones should be labeled ‘This could change your life.’",
    "Reading gives us someplace to go when we have to stay where we are.",
    "A capacity and taste for reading gives access to whatever has already been discovered by others.",
    "The reading of all good books is like a conversation with the finest minds of past centuries.",
    "Read in order to live.",
    "Books are lighthouses erected in the great sea of time.",
    "We lose ourselves in books, we find ourselves there too.",
    "Books are not made for furniture, but there is nothing else that so beautifully furnishes a house.",
    "Reading well is one of the great pleasures that solitude can afford you.",
    "The journey of a lifetime starts with the turning of a page.",
    "Reading is a conversation. All books talk. But a good book listens as well.",
    "Books don’t just go with you, they take you where you’ve never been.",
    "Reading is to the soul what food is to the body.",
    "Books are the carriers of civilization.",
    "It is what you read when you don't have to that determines what you will be when you can't help it.",
    "Reading is the key that opens doors to many good things in life.",
    "Books are uniquely portable magic.",
    "We read to taste life twice, in the moment and in retrospect.",
    "Reading gives you a better perspective of the world.",
    "I kept always two books in my pocket: one to read, one to write in.",
    "Books allow you to fully explore a topic and immerse yourself in a deeper way than most media today.",
    "The whole world opened up to me when I learned to read.",
    "Reading helps you slow down and find peace.",
    "The world belongs to those who read.",
    "You are not alone when you are reading a book.",
    "Reading strengthens your mind and your soul.",
    "A book is a device to ignite the imagination.",
    "Reading is a habit that can change your destiny.",
    "A child who reads will be an adult who thinks.",
    "You learn more from books than from any school.",
    "Books have the power to transform lives.",
    "To read is to empower.",
    "Through reading, we expand our world.",
    "Books can show us who we are.",
    "The best advice I ever got was that knowledge is power and to keep reading.",
    "Read more, know more, do more.",
    "Reading feeds your curiosity and fuels your dreams.",
    "Open a book and open your mind.",
    "In books, I have traveled, not only to other worlds, but into my own soul.",
    "Books are the great equalizer.",
    "Each book is a world, each page a journey.",
    "When in doubt, read a book.",
    "Good books never truly end — they live on in your heart.",
    "Reading unlocks your potential.",
    "Through books, we experience lives beyond our own.",
    "The person who reads lives thousands of lives; the one who doesn’t lives only one.",
    "Reading is the road to knowledge and the key to understanding.",
    "The more you read, the more empowered you become.",
  ];
  